# SSM Parameter Store for API validation token
# Token is randomly generated by Terraform

resource "random_password" "api_token" {
  length  = 32
  special = true
}

resource "aws_ssm_parameter" "api_token" {
  name        = "/${var.project_name}/api-token"
  description = "API validation token for microservice authentication"
  type        = "SecureString"
  value       = random_password.api_token.result

  tags = merge(
    var.tags,
    {
      Name = "${var.project_name}-api-token-${var.environment}"
    }
  )
}
